### ISSUE TITLE
How to build the library?

### ISSUE THREAD

**Issue by ddolcimascolo** [jmapio/jmap-js#1]
Hello,

Thanks a lot for releasing this!
Can you explain how to build the standalone jmap.js file from the sources?

Also, I can't seem to find any tests in the repository, are they located elsewhere?

Thanks again !

**Comment by neilj** [comment]
I've added a Makefile to the repository, so now all you need to do is call `make build`. You need to have node installed to build it.

There are no tests at the moment.
