### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by sk33wiff** [jmapio/jmap-js#2]
I'm trying to figure out how to use this library but even after going through and following the steps in the docs I can't manage to make it fire requests against my server.

After authenticating I'm calling:

``` javascript
JMAP.auth.didAuthenticate(account, accessToken, {
    "authenticationUrl" : "/mail/api/authenticate2",
    "apiUrl": "/mail/api/mail2",
    "uploadUrl": "/mail/api/upload",
    "eventSourceUrl": "/mail/api/events",
});
```

And then after:

``` javascript
JMAP.store.getQuery( 'inbox', JMAP.MessageList, { filter: { inMailboxes: [ JMAP.mail.systemMailboxIds.get( 'inbox' ) ] }, sort: [ 'date desc' ], collapseThreads: true });
```

But nothing seems to happen.

I also tried something like this but with no luck:

``` javascript
JMAP.store.getRecord(JMAP.Message, myMessageId);
```

Any thoughts?

UPDATE: requests are being sent after sometime they are made but I having trouble understanding how to have more control over the cycle.

**Comment by sk33wiff** [comment]
``` javascript
O.RunLoop.flushAllQueues();
```

Seems to do what I was looking for,

Cheers

**Comment by neilj** [comment]
This will work, although the idiomatic way of doing this is to wrap your app's code entry points (generally the event handlers) in a call to `O.RunLoop.invoke`; this is handled automatically if you use the Overture library to build the app. This ensures that you can make your API calls and store requests wherever you need them in the code, and the API requests are batched up and sent once everything else is done.

(Sorry for the late reply.)

**Comment by sk33wiff** [comment]
I see, thanks for your answer
