### ISSUE TITLE
Why has a: "A full JavaScript implementation of the JMAP data model" UI dependencies 

### ISSUE THREAD

**Issue by pmario** [jmapio/jmap-js#5]
At https://github.com/jmapio/jmap-js#dependencies you write: 

>JMAP-JS requires the Overture library's core, foundation, datastore, io, timezones, ua and localisation modules.
>
>To build the time zone data you will need a copy of the Olsen database. There is a script included with Overture to convert the raw data into the required format.

It may be understandable, that time-zone data is needed somewhere, BUT  why does it depend on UI and localisation elements. I did expect more like a "zero dependency" library.

**Comment by neilj** [comment]
It doesn't depend on the UI components. It depends on localisation because there are various error strings that may be exposed to the user; these could be removed.
