### ISSUE TITLE
 Some security findings

### ISSUE THREAD

**Issue by aileenscott-uleska** [jmapio/jmap-js#7]
Hi folks,

I hope you don’t mind, we were testing out our security automation tool and ran it against your project.  A few issues came out that you may want to check out - we weren’t sure how to submit a PDF here, so we uploaded it to https://source-security.co.uk/4a55f39c-b576-4882-a074-3da083f295a1/
Thanks.
Aileen

**Comment by neilj** [comment]
Hi Aileen. I've checked these and none of them are security issues, but thanks for running the test.
